import 'dart:io';
import 'dart:isolate';

import 'package:path/path.dart' as p;

import 'generated_file_tracker.dart';
import 'output_paths.dart';

/// Writes the static parts of the generated TypeScript client:
/// `package.json`, `tsconfig.json`, `.gitignore`, the `src/index.ts`
/// barrel, and the verbatim runtime under `src/runtime/`.
///
/// Tracks every file it writes via [GeneratedFileTracker] so the
/// caller can sweep orphans after model/endpoint emission has run.
class ScaffoldEmitter {
  ScaffoldEmitter({
    required this.outputPaths,
    required this.tracker,
  });

  final OutputPaths outputPaths;
  final GeneratedFileTracker tracker;

  Future<void> emit() async {
    outputPaths.outputDir.createSync(recursive: true);
    _writePackageJson();
    _writeTsconfig();
    _writeGitignore();
    _writeIndexBarrel();
    await _copyRuntime();
  }

  void _writePackageJson() {
    _writeRelative('package.json', _packageJsonContent());
  }

  void _writeTsconfig() {
    _writeRelative('tsconfig.json', _tsconfigContent());
  }

  void _writeGitignore() {
    _writeRelative('.gitignore', 'node_modules/\ndist/\n*.log\n');
  }

  void _writeIndexBarrel() {
    // For now the barrel re-exports only the runtime. Model and
    // endpoint emission (issues #5–#8) will append their re-exports
    // here at write-time.
    _writeRelative(
      'src/index.ts',
      "// Public surface of the generated client.\n"
      "export * from './runtime/index.js';\n",
    );
  }

  Future<void> _copyRuntime() async {
    final runtimeSrc = await _resolveRuntimeSource();
    final destDir = Directory(p.join(outputPaths.outputDir.path, 'src', 'runtime'));
    destDir.createSync(recursive: true);

    for (final entity in runtimeSrc.listSync(recursive: true)) {
      if (entity is! File) continue;
      if (!entity.path.endsWith('.ts')) continue;
      // Skip vitest test files; the consumer doesn't need them.
      if (entity.path.contains('${p.separator}__tests__${p.separator}')) {
        continue;
      }
      if (entity.path.endsWith('.test.ts')) continue;

      final relativePath = p.relative(entity.path, from: runtimeSrc.path);
      final destFile = File(p.join(destDir.path, relativePath));
      destFile.parent.createSync(recursive: true);
      destFile.writeAsStringSync(entity.readAsStringSync());
      tracker.recordWrite(destFile);
    }
  }

  /// Locates the runtime source files inside the package, regardless of
  /// whether the package is consumed via `dart pub add` (resolved out of
  /// the pub-cache) or via a path dependency (in-tree).
  Future<Directory> _resolveRuntimeSource() async {
    final uri = await Isolate.resolvePackageUri(
      Uri.parse('package:serverpod_typescript_bridge/runtime/typescript/src/'),
    );
    if (uri == null) {
      throw StateError(
        'Unable to resolve runtime source location. '
        'Is serverpod_typescript_bridge installed correctly?',
      );
    }
    return Directory.fromUri(uri);
  }

  void _writeRelative(String relativePath, String content) {
    final f = File(p.join(outputPaths.outputDir.path, relativePath));
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(content);
    tracker.recordWrite(f);
  }

  String _packageJsonContent() {
    return '''
{
  "name": "${outputPaths.packageName}",
  "version": "0.0.1",
  "description": "Generated by serverpod_typescript_bridge — do not edit by hand.",
  "type": "module",
  "private": true,
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    }
  },
  "scripts": {
    "build": "tsc",
    "typecheck": "tsc --noEmit"
  },
  "devDependencies": {
    "typescript": "^5.4.0"
  }
}
''';
  }

  String _tsconfigContent() {
    return '''
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "rootDir": "src",
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "lib": ["ES2022", "DOM"]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["dist", "node_modules"]
}
''';
  }
}
