import 'dart:io';
import 'dart:isolate';

import 'package:path/path.dart' as p;

import 'generated_file_tracker.dart';
import 'output_paths.dart';

/// Writes the static parts of the generated TypeScript client:
/// `package.json`, `tsconfig.json`, `.gitignore`, the `src/index.ts`
/// barrel, and the verbatim runtime under `src/runtime/`.
///
/// Tracks every file it writes via [GeneratedFileTracker] so the
/// caller can sweep orphans after model/endpoint emission has run.
class ScaffoldEmitter {
  ScaffoldEmitter({
    required this.outputPaths,
    required this.tracker,
    this.additionalBarrelExports = const [],
    this.moduleDependencies = const {},
  });

  final OutputPaths outputPaths;
  final GeneratedFileTracker tracker;

  /// Extra re-exports the barrel `src/index.ts` should include beyond
  /// the runtime — e.g. `./protocol/index.js` once model emission lands.
  final List<String> additionalBarrelExports;

  /// Maps npm package name → version-or-url string (typically
  /// `file:..` for sibling-generated module clients). Each entry
  /// becomes one `dependencies:` line in the generated `package.json`.
  final Map<String, String> moduleDependencies;

  Future<void> emit() async {
    outputPaths.outputDir.createSync(recursive: true);
    _writePackageJson();
    _writeTsconfig();
    _writeGitignore();
    _writeIndexBarrel();
    await _copyRuntime();
  }

  void _writePackageJson() {
    _writeRelative('package.json', _packageJsonContent());
  }

  void _writeTsconfig() {
    _writeRelative('tsconfig.json', _tsconfigContent());
  }

  void _writeGitignore() {
    _writeRelative('.gitignore', 'node_modules/\ndist/\n*.log\n');
  }

  void _writeIndexBarrel() {
    final lines = StringBuffer()
      ..writeln('// Public surface of the generated client.')
      ..writeln("export * from './runtime/index.js';");
    for (final extra in additionalBarrelExports) {
      lines.writeln("export * from '$extra';");
    }
    _writeRelative('src/index.ts', lines.toString());
  }

  Future<void> _copyRuntime() async {
    final runtimeSrc = await _resolveRuntimeSource();
    final destDir = Directory(p.join(outputPaths.outputDir.path, 'src', 'runtime'));
    destDir.createSync(recursive: true);

    for (final entity in runtimeSrc.listSync(recursive: true)) {
      if (entity is! File) continue;
      if (!entity.path.endsWith('.ts')) continue;
      // Skip vitest test files; the consumer doesn't need them.
      if (entity.path.contains('${p.separator}__tests__${p.separator}')) {
        continue;
      }
      if (entity.path.endsWith('.test.ts')) continue;

      final relativePath = p.relative(entity.path, from: runtimeSrc.path);
      final destFile = File(p.join(destDir.path, relativePath));
      destFile.parent.createSync(recursive: true);
      // Byte-level copy keeps the runtime truly verbatim — no BOM,
      // line-ending, or encoding drift if the source file has them.
      entity.copySync(destFile.path);
      tracker.recordWrite(destFile);
    }
  }

  /// Locates the runtime source files inside the package, regardless of
  /// whether the package is consumed via `dart pub add` (resolved out of
  /// the pub-cache) or via a path dependency (in-tree).
  Future<Directory> _resolveRuntimeSource() async {
    final uri = await Isolate.resolvePackageUri(
      Uri.parse('package:serverpod_typescript_bridge/runtime/typescript/src/'),
    );
    if (uri == null) {
      throw StateError(
        'Unable to resolve runtime source location. '
        'Is serverpod_typescript_bridge installed correctly?',
      );
    }
    return Directory.fromUri(uri);
  }

  void _writeRelative(String relativePath, String content) {
    final f = File(p.join(outputPaths.outputDir.path, relativePath));
    f.parent.createSync(recursive: true);
    f.writeAsStringSync(content);
    tracker.recordWrite(f);
  }

  String _packageJsonContent() {
    final depsBlock = moduleDependencies.isEmpty
        ? ''
        : '  "dependencies": ${_formatDeps(moduleDependencies)},\n';
    return '''
{
  "name": "${outputPaths.packageName}",
  "version": "0.0.1",
  "description": "Generated by serverpod_typescript_bridge — do not edit by hand.",
  "type": "module",
  "private": true,
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    }
  },
  "scripts": {
    "build": "tsc",
    "typecheck": "tsc --noEmit"
  },
$depsBlock  "devDependencies": {
    "typescript": "^5.4.0"
  }
}
''';
  }

  /// Inline the deps map as a stable, alphabetised JSON object.
  String _formatDeps(Map<String, String> deps) {
    final keys = deps.keys.toList()..sort();
    final lines = <String>[];
    for (final k in keys) {
      lines.add('    "$k": "${deps[k]}"');
    }
    return '{\n${lines.join(',\n')}\n  }';
  }

  String _tsconfigContent() {
    return '''
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "rootDir": "src",
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "lib": ["ES2022", "DOM"]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["dist", "node_modules"]
}
''';
  }
}
